language: java

jdk:
  - oraclejdk8

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/

install: echo "skip 'gradle assemble' step"
script: gradle build --continue
after_success:
  - bash <(curl -s https://codecov.io/bash)